### ISSUE TITLE
Trust SSH host on first use enabled by default

### ISSUE THREAD

**Issue by pieterlange** [kuberhost/kube-backup#3]
Its fairly easy to execute a MiTM attack on deployments of this project because by default there's no preseeded SSH `known_hosts` file. [This is bad](https://bridge.grumpy-troll.org/2017/04/golang-ssh-security/).

Instead, the `known_hosts` file gets seeded with whatever the public key of the host is at runtime. Because of the ephemeral nature of containers, this basically means this happens on every run.
https://github.com/kuberhost/kube-backup/blob/d27f3956bfe38c037d8714f4a8d052f3e64bc9f8/lib/kube_backup/writter.rb#L162

If you want to improve UX, you could preseed some SSH keys from EG github.com, bitbucket etc. but as-is this configuration is pretty unsafe.

**Comment by Paxa** [comment]
It would check if `known_hosts` already exist and have host for git then `ssh-keyscan` won't run.
I thought about providing `known_hosts` with keys for github, gitlab, bitbucket, etc. But those services may change their ssh certificate some day and it will stop working

For now we can provide `known_hosts` via mounting configmap or secret or volume

Any suggestions for proper solution?

**Comment by pieterlange** [comment]
Don't fail in a "usable" state but force the users to supply a `known_hosts` file. Or persist the `known_hosts` file in a kubernetes resource (eg configmap or secret) and write that on first use.

**Comment by pieterlange** [comment]
> But those services may change their ssh certificate some day and it will stop working

This would be a highly newsworthy event and much is much more likely to be picked up by sysadmins than a single MittM attack for one of the cronjob runs, capturing your entire cluster state.

**Comment by Paxa** [comment]
Partially fixed by https://github.com/kuberhost/kube-backup/commit/51494863253bccc5df7819e15f40608083c84793
