### ISSUE TITLE
Use subdir within repo

### ISSUE THREAD

**Issue by tewing-riffyn** [kuberhost/kube-backup#4]
It would be great if there were an ENV variable like GIT_SUBDIR I could set to the clustername and all files would be created under this directory.  This would allow me to backup multiple clusters to one git repo

**Comment by Paxa** [comment]
That's good idea, I will try to add soon, also git branch variable

**Comment by Paxa** [comment]
Fixed in https://github.com/kuberhost/kube-backup/commit/d44324f255df50c5d001acec8218fd8420cdcd3b
You may use `GIT_PREFIX` and `GIT_BRANCH`
