### ISSUE TITLE
Not working when Grafana is not available

### ISSUE THREAD

**Issue by futureCreator** [kuberhost/kube-backup#5]
Backup not working when Grafana plugin is enable and Grafana is not available, 
e.g. 503 Service Temporarily Unavailable

In my opinion, add some skip grafana plugin logic when grafana is not available in `run` method of `grafana.rb`.

```ruby
# grafana.rb
# TODO: add check grafana status
if !@grafana_url || @grafana_url == ''
  KubeBackup.logger.info "Skip Grafana plugin"
  return
end
```

**Comment by Paxa** [comment]
Agree, should not stop when grafana not available. But if we just skip it then all grafana files will be delete from git...
Probably need to copy to tmp folder and then put it back. Will try to implement later

**Comment by Paxa** [comment]
Should be fixed by https://github.com/kuberhost/kube-backup/commit/45e491dcfa8776e8da6a02ffc6f1c00d79be66e5
